namespace Domain.Enums;

public enum SiteType
{
    Other = 1,
    Historical = 2,
    Museum = 3,
    Religious = 4,
    Archaeological = 5,
    Cultural = 6,
    Natural = 7,
    Entertainment = 8,
    Monument = 9,
    Palace = 10,
    Temple = 11,
    Park = 12,
    Zoo = 13,
    Aquarium = 14,
    BotanicalGarden = 15,
    Castle = 16,
    Fortress = 17,
    Gallery = 18,
    Library = 19,
    Theater = 20,
    Stadium = 21,
    Beach = 22,
    Mountain = 23,
    Lake = 24,
    River = 25,
    Waterfall = 26,
    Cave = 27,
    Volcano = 28,
    Desert = 29,
    Island = 30,
    Gate = 31,
    Therapeutic = 32,
    DivingSite = 33,
    Marina = 34,
    Walkway = 35
}