// <auto-generated />
using System;
using Infrastructure.Persistence.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.ApplicationContext.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502211027_NullableNationalityAndCityImage")]
    partial class NullableNationalityAndCityImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rafeeq")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Common.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Infrastructure.Identity.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "rafeeq");

                    b.HasDiscriminator<string>("UserRole").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "rafeeq");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "rafeeq");
                });

            modelBuilder.Entity("Domain.Common.BaseAuditableEntity", b =>
                {
                    b.HasBaseType("Domain.Common.BaseEntity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedAt");

                    b.HasIndex("LastModifiedBy");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.Tourist", b =>
                {
                    b.HasBaseType("Domain.Common.BaseEntity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tourists_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tourists_Status");

                    b.ToTable("Tourists", "rafeeq");
                });

            modelBuilder.Entity("Infrastructure.Identity.Entities.StaffUser", b =>
                {
                    b.HasBaseType("Infrastructure.Identity.Entities.ApplicationUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasDiscriminator().HasValue("StaffUser");
                });

            modelBuilder.Entity("Infrastructure.Identity.Entities.TouristUser", b =>
                {
                    b.HasBaseType("Infrastructure.Identity.Entities.ApplicationUser");

                    b.HasDiscriminator().HasValue("Tourist");
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.Artifact", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Artifacts_DisplayOrder");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_Artifacts_SiteId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Artifacts_Type");

                    b.ToTable("Artifacts", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.ArtifactImage", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasIndex("ArtifactId", "DisplayOrder")
                        .HasDatabaseName("IX_ArtifactImages_ArtifactId_DisplayOrder");

                    b.HasIndex("ArtifactId", "IsMain")
                        .HasDatabaseName("IX_ArtifactImages_ArtifactId_IsMain");

                    b.ToTable("ArtifactImages", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.ArtifactLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ArtifactLocalizedContents_Name");

                    b.HasIndex("ArtifactId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_ArtifactLocalizedContents_ArtifactId_Language")
                        .HasFilter("[ArtifactId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("ArtifactLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.Attraction", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("_historicalPeriods")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("HistoricalPeriods");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("IX_Attractions_IsFeatured");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_Attractions_SiteId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Attractions_Type");

                    b.ToTable("Attractions", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.AttractionImage", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasIndex("AttractionId", "DisplayOrder")
                        .HasDatabaseName("IX_AttractionImages_AttractionId_DisplayOrder");

                    b.HasIndex("AttractionId", "IsMain")
                        .HasDatabaseName("IX_AttractionImages_AttractionId_IsMain");

                    b.ToTable("AttractionImages", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.AttractionLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_AttractionLocalizedContents_Name");

                    b.HasIndex("AttractionId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_AttractionLocalizedContents_AttractionId_Language")
                        .HasFilter("[AttractionId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("AttractionLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.CityAggregate.City", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("TotalSites")
                        .HasColumnType("int");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Cities_DisplayOrder");

                    b.ToTable("Cities", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.CityAggregate.CityLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_CityLocalizedContents_Name");

                    b.HasIndex("CityId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_CityLocalizedContents_CityId_Language")
                        .HasFilter("[CityId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("CityLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.ContentReportAggregate.ContentReport", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int?>("ActionTaken")
                        .HasColumnType("int");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("IX_ContentReports_ContentId");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_ContentReports_Priority");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("IX_ContentReports_ReportedAt");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("IX_ContentReports_ReportedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ContentReports_Status");

                    b.ToTable("ContentReports", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.ReviewAggregate.Review", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<int>("NotHelpfulCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_Reviews_SiteId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reviews_Status");

                    b.HasIndex("TouristId")
                        .HasDatabaseName("IX_Reviews_TouristId");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("IX_Reviews_SiteId_Status");

                    b.ToTable("Reviews", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.NearestTransportation", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<bool>("HasAccessibility")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("SiteId", "Type")
                        .HasDatabaseName("IX_NearestTransportations_SiteId_Type");

                    b.ToTable("NearestTransportations", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.NearestTransportationLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TransportationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_NearestTransportationLocalizedContents_Name");

                    b.HasIndex("TransportationId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_NearestTransportationLocalizedContents_TransportationId_Language")
                        .HasFilter("[TransportationId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("NearestTransportationLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.Site", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHiddenGem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRating")
                        .HasColumnType("int");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("_facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Facilities");

                    b.HasIndex("AverageRating")
                        .HasDatabaseName("IX_Sites_AverageRating");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Sites_CityId");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("IX_Sites_IsFeatured");

                    b.HasIndex("IsHiddenGem")
                        .HasDatabaseName("IX_Sites_IsHiddenGem");

                    b.HasIndex("IsPopular")
                        .HasDatabaseName("IX_Sites_IsPopular");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Sites_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Sites_Type");

                    b.ToTable("Sites", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.SiteImage", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SiteId", "DisplayOrder")
                        .HasDatabaseName("IX_SiteImages_SiteId_DisplayOrder");

                    b.HasIndex("SiteId", "IsMain")
                        .HasDatabaseName("IX_SiteImages_SiteId_IsMain");

                    b.ToTable("SiteImages", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.SiteLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryTicketNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_SiteLocalizedContents_Name");

                    b.HasIndex("Language", "Name")
                        .HasDatabaseName("IX_SiteLocalizedContents_Language_Name");

                    b.HasIndex("SiteId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_SiteLocalizedContents_SiteId_Language")
                        .HasFilter("[SiteId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("SiteLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Offer", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("int");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RedemptionCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PromoCode")
                        .HasDatabaseName("IX_Offers_PromoCode");

                    b.HasIndex("SponsorId", "IsActive")
                        .HasDatabaseName("IX_Offers_SponsorId_IsActive");

                    b.ToTable("Offers", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.OfferLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_OfferLocalizedContents_Title");

                    b.HasIndex("OfferId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_OfferLocalizedContents_OfferId_Language")
                        .HasFilter("[OfferId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("OfferLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Sponsor", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("TotalRedemptions")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Sponsors_Status");

                    b.HasIndex("Tier")
                        .HasDatabaseName("IX_Sponsors_Tier");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Sponsors_Type");

                    b.ToTable("Sponsors", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.SponsorImage", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SponsorId", "DisplayOrder")
                        .HasDatabaseName("IX_SponsorImages_SponsorId_DisplayOrder");

                    b.HasIndex("SponsorId", "IsMain")
                        .HasDatabaseName("IX_SponsorImages_SponsorId_IsMain");

                    b.ToTable("SponsorImages", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.SponsorLocalizedContent", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_SponsorLocalizedContents_Title");

                    b.HasIndex("Language", "Title")
                        .HasDatabaseName("IX_SponsorLocalizedContents_Language_Title");

                    b.HasIndex("SponsorId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_SponsorLocalizedContents_SponsorId_Language")
                        .HasFilter("[SponsorId] IS NOT NULL AND [Language] IS NOT NULL");

                    b.ToTable("SponsorLocalizedContents", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.FavouriteSite", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("SiteId");

                    b.HasIndex("TouristId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_Favourites_TouristId_SiteId")
                        .HasFilter("[TouristId] IS NOT NULL AND [SiteId] IS NOT NULL");

                    b.ToTable("Favourites", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.VisitedSite", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("SiteId");

                    b.HasIndex("TouristId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_VisitedSites_TouristId_SiteId")
                        .HasFilter("[TouristId] IS NOT NULL AND [SiteId] IS NOT NULL");

                    b.ToTable("VisitedSites", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.Trip", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedTotalDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PreferredTransportation")
                        .HasColumnType("int");

                    b.Property<int>("ShareCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Trips_IsPublic");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Trips_Name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Trips_Status");

                    b.HasIndex("TouristId")
                        .HasDatabaseName("IX_Trips_TouristId");

                    b.ToTable("Trips", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.TripNote", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_TripNotes_TripId");

                    b.ToTable("TripNotes", "rafeeq");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.TripSite", b =>
                {
                    b.HasBaseType("Domain.Common.BaseAuditableEntity");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualVisitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_TripSites_SiteId");

                    b.HasIndex("TripId", "DisplayOrder")
                        .HasDatabaseName("IX_TripSites_TripId_DisplayOrder");

                    b.HasIndex("TripId", "VisitDate")
                        .HasDatabaseName("IX_TripSites_TripId_VisitDate");

                    b.ToTable("TripSites", "rafeeq");
                });

            modelBuilder.Entity("Infrastructure.Identity.Entities.AdminUser", b =>
                {
                    b.HasBaseType("Infrastructure.Identity.Entities.StaffUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Infrastructure.Identity.Entities.ModeratorUser", b =>
                {
                    b.HasBaseType("Infrastructure.Identity.Entities.StaffUser");

                    b.HasDiscriminator().HasValue("Moderator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.Artifact", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.ArtifactImage", b =>
                {
                    b.HasOne("Domain.Entities.ArtifactAggregate.Artifact", null)
                        .WithMany("Images")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("ArtifactImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("ArtifactImageId");

                            b1.ToTable("ArtifactImages", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("ArtifactImageId");
                        });

                    b.Navigation("StorageKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.ArtifactLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.ArtifactAggregate.Artifact", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.Attraction", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("AttractionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.AttractionImage", b =>
                {
                    b.HasOne("Domain.Entities.AttractionAggregate.Attraction", null)
                        .WithMany("Images")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("AttractionImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("AttractionImageId");

                            b1.ToTable("AttractionImages", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("AttractionImageId");
                        });

                    b.Navigation("StorageKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.AttractionLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.AttractionAggregate.Attraction", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CityAggregate.City", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.GeoLocation", "CenterLocation", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("CenterLocation")
                        .IsRequired();

                    b.Navigation("StorageKey");
                });

            modelBuilder.Entity("Domain.Entities.CityAggregate.CityLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.CityAggregate.City", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ReviewAggregate.Review", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TouristAggregate.Tourist", "Tourist")
                        .WithMany()
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Rating");

                            b1.HasKey("ReviewId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Reviews_Rating");

                            b1.ToTable("Reviews", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId");
                        });

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.NearestTransportation", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany("NearestTransportations")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("NearestTransportationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("NearestTransportationId");

                            b1.ToTable("NearestTransportations", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("NearestTransportationId");
                        });

                    b.OwnsOne("Domain.ValueObjects.TimeRange", "OperatingHours", b1 =>
                        {
                            b1.Property<Guid>("NearestTransportationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("time")
                                .HasColumnName("EndTime");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("time")
                                .HasColumnName("StartTime");

                            b1.HasKey("NearestTransportationId");

                            b1.ToTable("NearestTransportations", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("NearestTransportationId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.NearestTransportationLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.NearestTransportation", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("TransportationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("NearestTransportationLocalizedContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Address");

                            b1.HasKey("NearestTransportationLocalizedContentId");

                            b1.ToTable("NearestTransportationLocalizedContents", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("NearestTransportationLocalizedContentId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.Site", b =>
                {
                    b.HasOne("Domain.Entities.CityAggregate.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("SiteId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_Sites_Location_Latitude_Longitude");

                            b1.ToTable("Sites", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");
                        });

                    b.OwnsMany("Domain.ValueObjects.OpeningHour", "OpeningHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("bit")
                                .HasColumnName("IsClosed");

                            b1.Property<Guid>("SiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SiteId", "Day")
                                .IsUnique()
                                .HasDatabaseName("IX_Sites_OpeningHours_SiteId_DayOfWeek");

                            b1.ToTable("Site_OpeningHours", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");

                            b1.OwnsOne("Domain.ValueObjects.TimeRange", "OpeningTime", b2 =>
                                {
                                    b2.Property<int>("OpeningHourId")
                                        .HasColumnType("int");

                                    b2.Property<TimeSpan>("EndTime")
                                        .HasColumnType("time")
                                        .HasColumnName("EndTime");

                                    b2.Property<TimeSpan>("StartTime")
                                        .HasColumnType("time")
                                        .HasColumnName("StartTime");

                                    b2.HasKey("OpeningHourId");

                                    b2.ToTable("Site_OpeningHours", "rafeeq");

                                    b2.WithOwner()
                                        .HasForeignKey("OpeningHourId");
                                });

                            b1.Navigation("OpeningTime")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.ValueObjects.Ticket", "EntryTicket", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("_exists")
                                .HasColumnType("bit")
                                .HasColumnName("TicketExists");

                            b1.HasKey("SiteId");

                            b1.ToTable("Sites", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");

                            b1.OwnsOne("Domain.ValueObjects.Money", "EgyptianPrice", b2 =>
                                {
                                    b2.Property<Guid>("TicketSiteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("EgyptianPrice_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("EgyptianPrice_Currency");

                                    b2.HasKey("TicketSiteId");

                                    b2.ToTable("Sites", "rafeeq");

                                    b2.WithOwner()
                                        .HasForeignKey("TicketSiteId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Money", "ForeignerPrice", b2 =>
                                {
                                    b2.Property<Guid>("TicketSiteId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("ForeignerPrice_Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("ForeignerPrice_Currency");

                                    b2.HasKey("TicketSiteId");

                                    b2.ToTable("Sites", "rafeeq");

                                    b2.WithOwner()
                                        .HasForeignKey("TicketSiteId");
                                });

                            b1.Navigation("EgyptianPrice")
                                .IsRequired();

                            b1.Navigation("ForeignerPrice");
                        });

                    b.Navigation("City");

                    b.Navigation("EntryTicket");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.SiteImage", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany("Images")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("SiteImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("SiteImageId");

                            b1.ToTable("SiteImages", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SiteImageId");
                        });

                    b.Navigation("StorageKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.SiteLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SiteLocalizedContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Address");

                            b1.HasKey("SiteLocalizedContentId");

                            b1.ToTable("SiteLocalizedContents", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SiteLocalizedContentId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Offer", b =>
                {
                    b.HasOne("Domain.Entities.SponsorAggregate.Sponsor", "Sponsor")
                        .WithMany("Offers")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Money", "DiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Price_Currency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("Domain.ValueObjects.DateRange", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("OfferId");

                            b1.HasIndex("StartDate", "EndDate")
                                .HasDatabaseName("IX_Offers_ValidityPeriod_StartDate_EndDate");

                            b1.ToTable("Offers", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("DiscountAmount");

                    b.Navigation("Sponsor");

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.OfferLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.SponsorAggregate.Offer", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Sponsor", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.DateRange", "ContractDate", b1 =>
                        {
                            b1.Property<Guid>("SponsorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("SponsorId");

                            b1.HasIndex("EndDate")
                                .HasDatabaseName("IX_Sponsors_ContractDate_EndDate");

                            b1.ToTable("Sponsors", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorId");
                        });

                    b.OwnsOne("Domain.ValueObjects.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("SponsorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("float(9)")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("SponsorId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_Sponsors_Location_Latitude_Longitude");

                            b1.ToTable("Sponsors", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Email", "ContactEmail", b1 =>
                        {
                            b1.Property<Guid>("SponsorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("ContactEmail");

                            b1.HasKey("SponsorId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Sponsors_ContactEmail");

                            b1.ToTable("Sponsors", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PhoneNumber", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("SponsorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("SponsorId");

                            b1.ToTable("Sponsors", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorId");
                        });

                    b.Navigation("ContactEmail");

                    b.Navigation("ContactPhone");

                    b.Navigation("ContractDate")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.SponsorImage", b =>
                {
                    b.HasOne("Domain.Entities.SponsorAggregate.Sponsor", null)
                        .WithMany("Images")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.StorageKey", "StorageKey", b1 =>
                        {
                            b1.Property<Guid>("SponsorImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("StorageKey");

                            b1.HasKey("SponsorImageId");

                            b1.ToTable("SponsorImages", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorImageId");
                        });

                    b.Navigation("StorageKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.SponsorLocalizedContent", b =>
                {
                    b.HasOne("Domain.Entities.SponsorAggregate.Sponsor", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SponsorLocalizedContentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Address");

                            b1.HasKey("SponsorLocalizedContentId");

                            b1.ToTable("SponsorLocalizedContents", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("SponsorLocalizedContentId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.FavouriteSite", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TouristAggregate.Tourist", null)
                        .WithMany("Favourites")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.VisitedSite", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TouristAggregate.Tourist", null)
                        .WithMany("VisitedSites")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("VisitedSiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Rating");

                            b1.HasKey("VisitedSiteId");

                            b1.ToTable("VisitedSites", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("VisitedSiteId");
                        });

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.Trip", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Money", "ActualCost", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ActualCost_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ActualCost_Currency");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("Domain.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Money", "EstimatedBudget", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("EstimatedBudget_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("EstimatedBudget_Currency");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("ActualCost");

                    b.Navigation("DateRange")
                        .IsRequired();

                    b.Navigation("EstimatedBudget");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.TripNote", b =>
                {
                    b.HasOne("Domain.Entities.TripAggregate.Trip", null)
                        .WithMany("Notes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.TripSite", b =>
                {
                    b.HasOne("Domain.Entities.SiteAggregate.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TripAggregate.Trip", null)
                        .WithMany("Sites")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.TimeRange", "VisitTimeRange", b1 =>
                        {
                            b1.Property<Guid>("TripSiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("time")
                                .HasColumnName("EndTime");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("time")
                                .HasColumnName("StartTime");

                            b1.HasKey("TripSiteId");

                            b1.ToTable("TripSites", "rafeeq");

                            b1.WithOwner()
                                .HasForeignKey("TripSiteId");
                        });

                    b.Navigation("VisitTimeRange");
                });

            modelBuilder.Entity("Domain.Entities.TouristAggregate.Tourist", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("VisitedSites");
                });

            modelBuilder.Entity("Domain.Entities.ArtifactAggregate.Artifact", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LocalizedContents");
                });

            modelBuilder.Entity("Domain.Entities.AttractionAggregate.Attraction", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LocalizedContents");
                });

            modelBuilder.Entity("Domain.Entities.CityAggregate.City", b =>
                {
                    b.Navigation("LocalizedContents");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.NearestTransportation", b =>
                {
                    b.Navigation("LocalizedContents");
                });

            modelBuilder.Entity("Domain.Entities.SiteAggregate.Site", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LocalizedContents");

                    b.Navigation("NearestTransportations");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Offer", b =>
                {
                    b.Navigation("LocalizedContents");
                });

            modelBuilder.Entity("Domain.Entities.SponsorAggregate.Sponsor", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LocalizedContents");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Domain.Entities.TripAggregate.Trip", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
